### add user
POST localhost:8080/users
Content-Type: application/json

{
  "id": "",
  "name": "Vincent, Huang",
  "age": 100
}

### find user by age
GET localhost:8080/users?age=100

### modify user
PUT localhost:8080/users
Content-Type: application/json

{
  "id": "605abba5311e820be8010243",
  "name": "Hans, Huang",
  "age": 100
}

### delete user by id
DELETE localhost:8080/users?id=605abb86311e820be8010242
