version: '3'

services:
  redis:
    image: redis:6
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    expose:
      - 5672
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

  mysql: # root/rootroot
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default

  mongo:
    image: mongo:4-bionic
    environment:
      - MONGODB_USER=root
      - MONGODB_PASS=rootroot
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - default

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootroot
    ports:
      - "8081:8081"
    networks:
      - default
    depends_on:
      - mongo

networks:
  default:
