### add user
POST localhost:8080/user
Content-Type: application/json

{
  "id": "",
  "name": "Vincent, Huang",
  "age": 888
}

### find user by id
GET localhost:8080/user?id=1

### modify user
PUT localhost:8080/user
Content-Type: application/json

{
  "id": 1,
  "name": "Vincent, Huang",
  "age": 88
}

### delete user by id
DELETE localhost:8080/user?id=1