###
POST http://localhost:8080/auth
Content-Type: application/json

{
  "userName": "wade9876",
  "password": "aaaa0000"
}

###
POST http://localhost:8080/members
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJqaWFubWluaHVhbmcuY2MiLCJzdWIiOiJ3YWRlOTg3NiIsImV4cCI6MTYzMjM3MjIxMywibmJmIjoxNjMyMzcwNDEzLCJpYXQiOjE2MzIzNzA0MTMsImp0aSI6ImMyNzk4MGNiLTkyNTAtNDQ4Yy05ZGYyLWViZGE0NzhkNGU3MiJ9.xoRdLMxsw4P2kHuBkuAgE8qIzSZKwjwOOuaaOLMHnOlyVbwhlyESxPhlkrvcOoWqBQ_DbwR1N4vAHzLUuqHjNg
Content-Type: application/json

{
  "uid": "wade9876666",
  "password": "aaaa0000",
  "role": "ROLE_OP"
}