###
POST http://localhost:8080/auth
Content-Type: application/json

{
  "userName": "admin",
  "password": "123456"
}

###
POST http://localhost:8080/members
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJqaWFubWluaHVhbmcuY2MiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTYzMjM3NzU0NCwibmJmIjoxNjMyMzc1NzQ0LCJpYXQiOjE2MzIzNzU3NDQsImp0aSI6ImRkOTE5Nzg3LWJiYTctNDE3OS04YTJjLTZhYzY3N2ZjOGQ0ZiJ9.t7roVrO2baZGZJauB2nVC7g7VuvS6KT6Mixqs1bChEJk7q5E-7rRLATJC0njGSQ0z1ptShvmYRnhSJHqPI2J2g
Content-Type: application/json

{
  "uid": "Vincent888",
  "password": "abcd5",
  "role": "ROLE_ADMIN"
}