version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - default

  elastic-kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS="http://elastic-elasticsearch:9200"
    networks:
      - default
    depends_on:
      - elastic-elasticsearch

  elastic-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - default

  elastic-logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    ports:
      - "5000:5000"
      - "12201:12201/udp"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - default
    depends_on:
      - elastic-kibana

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.16.0
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    restart: on-failure
    networks:
      - default
    depends_on:
      - jaeger-cassandra-schema

  jaeger-query:
    image: jaegertracing/jaeger-query:1.16.0
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    networks:
      - default
    depends_on:
      - jaeger-agent

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.16.0
    command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    networks:
      - default
    depends_on:
      - jaeger-collector

  jaeger-cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:${jaeger_version}
    networks:
      - default
    depends_on:
      - cassandra

networks:
  default:
