###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Wade, Wu",
  "age": 15,
  "gender": "BOY",
  "balance": 10000.0
}

###
GET http://localhost:8080/users/firstName/Wade

###
GET http://localhost:8080/users?lastName=Huang&page=0&size=5&column=id&direction=ASC

###
PATCH http://localhost:8080/users
Content-Type: application/json

{
  "id": 1,
  "age": 50
}

