###
POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Vincent",
  "lastName": "Huang",
  "age": 12,
  "gender": "BOY",
  "balance": 1000.0
}

###
GET http://localhost:8080/users/100

###
GET http://localhost:8080/users?lastName=Huang&page=1&size=6&column=id&direction=ASC

###
PATCH http://localhost:8080/users
Content-Type: application/json

{
  "id": 1,
  "age": 100
}